[package]
name = "spec_tests"
version = "0.1.0"
edition = { workspace = true }
authors = ["Sigma Prime <contact@sigmaprime.io>"]

[dependencies]
async-channel = { workspace = true }
base64 = { workspace = true }
bls = { workspace = true }
database = { workspace = true }
duties_tracker = { workspace = true }
ethereum_ssz = { workspace = true }
ethereum_ssz_derive = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
message_validator = { workspace = true }
openssl = { workspace = true }
operator_key = { path = "../common/operator_key" }
parking_lot = { workspace = true }
qbft = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
slot_clock = { workspace = true }
ssv_types = { workspace = true }
task_executor = { workspace = true }
tempfile = "3.10"
tokio = { workspace = true }
tree_hash = { workspace = true }
tree_hash_derive = { workspace = true }
types = { workspace = true }
walkdir = "2.5.0"
